const swaggerJSDoc = require("swagger-jsdoc");

const operation = (summary, secured = true) => ({ summary, tags: [summary.split(" ")[0]], ...(secured ? { security: [{ bearerAuth: [] }] } : {}), responses: { 200: { description: "Successful response" }, 400: { $ref: "#/components/responses/BadRequest" }, 401: { $ref: "#/components/responses/Unauthorized" }, 500: { $ref: "#/components/responses/InternalError" } } });
const paths = {};
const add = (path, method, summary, secured = true) => { paths[path] ||= {}; paths[path][method] = operation(summary, secured); };
[
  ["/health/live", "get", "Health liveness", false], ["/health/ready", "get", "Health readiness", false],
  ["/auth/register", "post", "Authentication register", false], ["/auth/login", "post", "Authentication login", false], ["/auth/logout", "post", "Authentication logout", false], ["/auth/logout-all", "post", "Authentication logout all"], ["/auth/refresh-token", "post", "Authentication refresh token", false], ["/auth/forgot-password", "post", "Authentication forgot password", false], ["/auth/reset-password", "post", "Authentication reset password", false],
  ["/attendance/punch-in", "post", "Attendance punch in"], ["/attendance/punch-out", "post", "Attendance punch out"], ["/attendance/me", "get", "Attendance history"], ["/attendance/team", "get", "Attendance team"], ["/attendance/all", "get", "Attendance organization"], ["/attendance/{id}/correct", "put", "Attendance correction"], ["/audit-logs/attendance/{attendanceId}", "get", "Attendance audit logs"],
  ["/leaves/types", "get", "Leave types"], ["/leaves/types", "post", "Leave type create"], ["/leaves/types/{id}", "put", "Leave type update"], ["/leaves/balance/me", "get", "Leave balance mine"], ["/leaves/balances", "get", "Leave balances"], ["/leaves/balances/allocate", "post", "Leave balance allocate"], ["/leaves/apply", "post", "Leave apply with document upload"], ["/leaves/me", "get", "Leave history mine"], ["/leaves/team", "get", "Leave history team"], ["/leaves/all", "get", "Leave history organization"], ["/leaves/{id}/document", "get", "Document upload download"], ["/leaves/{id}/history", "get", "Leave request history"], ["/leaves/{id}/approve", "put", "Leave approve"], ["/leaves/{id}/reject", "put", "Leave reject"], ["/leaves/{id}/cancel", "put", "Leave cancel"],
  ["/users/me", "get", "Employee profile mine"], ["/users/me", "put", "Employee profile update"], ["/users/me/profile-picture", "put", "Profile picture upload"], ["/users", "get", "Employee list"], ["/users/{id}", "get", "Employee detail"], ["/users/{id}", "put", "Employee update"], ["/users/{id}/status", "put", "Employee status"], ["/users/{id}/manager", "put", "Employee manager"], ["/users/{id}/department", "put", "Employee department"], ["/users/{id}/role", "put", "Employee role"],
  ["/departments", "get", "Department list"], ["/departments", "post", "Department create"], ["/departments/{id}", "get", "Department detail"], ["/departments/{id}", "put", "Department update"], ["/departments/{id}", "delete", "Department delete"], ["/dashboard/me", "get", "Dashboard employee"], ["/dashboard/team", "get", "Dashboard team"], ["/dashboard/organization", "get", "Dashboard organization"], ["/reports/attendance", "get", "Reports attendance"], ["/reports/leaves", "get", "Reports leaves"], ["/reports/export", "get", "Reports export"], ["/notifications/me", "get", "Notifications mine"], ["/notifications/test", "post", "Notifications test"], ["/automation/run/{jobName}", "post", "Automation run"],
].forEach(([path, method, summary, secured]) => add(path, method, summary, secured));

module.exports = swaggerJSDoc({ definition: { openapi: "3.0.3", info: { title: "Leave & Attendance API", version: "1.1.0", description: "Production API reference. All API routes are prefixed with /api." }, servers: [{ url: "/api" }], components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } }, responses: { BadRequest: { description: "Invalid request", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } }, }, Unauthorized: { description: "Authentication required" }, InternalError: { description: "Internal server error" } }, schemas: { Error: { type: "object", required: ["success", "message"], properties: { success: { type: "boolean", example: false }, message: { type: "string" } } } } }, paths }, apis: [] });
