import { Bell, Clock3 } from "lucide-react";
import Card from "../ui/Card";
import EmptyState from "../common/EmptyState";
import Badge from "../ui/Badge";

const toneForStatus = (status) => status === "approved" || status === "sent" ? "success" : status === "pending" || status === "queued" ? "warning" : status === "rejected" || status === "failed" ? "danger" : "neutral";
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—";

export function RecentNotifications({ notifications }) { const items = notifications?.notifications || []; return <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">Recent Notifications</h2><Bell size={18} className="text-slate-400" /></div>{items.length ? <div className="mt-4 divide-y divide-slate-100">{items.map((item) => <div key={item._id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium capitalize text-slate-800">{item.type?.replaceAll("_", " ") || "Notification"}</p><p className="mt-0.5 text-xs text-slate-500">{formatDate(item.createdAt)}</p></div><Badge tone={toneForStatus(item.status)}>{item.status}</Badge></div>)}</div> : <EmptyState title="No notifications" description="Your latest updates will appear here." />}</Card>; }

export function RecentLeaveRequests({ requests }) { const items = requests?.leaveRequests || []; return <Card className="p-5"><h2 className="font-semibold text-slate-900">Recent Leave Requests</h2>{items.length ? <div className="mt-4 divide-y divide-slate-100">{items.map((item) => { const user = item.userId; return <div key={item._id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-800">{user?.name || item.leaveTypeId?.name || "Leave request"}</p><p className="mt-0.5 text-xs text-slate-500">{user ? item.leaveTypeId?.name : `${formatDate(item.startDate)} – ${formatDate(item.endDate)}`}</p></div><Badge tone={toneForStatus(item.status)}>{item.status}</Badge></div>; })}</div> : <EmptyState title="No leave requests" description="Recent leave requests will appear here." />}</Card>; }

export function RecentActivity({ activity, role }) { const items = activity || []; return <Card className="p-5"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">Recent Activity</h2><Clock3 size={18} className="text-slate-400" /></div>{items.length ? <div className="mt-4 divide-y divide-slate-100">{items.map((item) => <div key={item._id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-slate-800">{item.employee?.name || (role === "employee" ? "Attendance record" : "Team attendance record")}</p><p className="mt-0.5 text-xs text-slate-500">{formatDate(item.date)}</p></div><Badge tone={item.status === "present" ? "success" : item.status === "absent" ? "danger" : "warning"}>{item.status}</Badge></div>)}</div> : <EmptyState title="No recent activity" description="Attendance updates will appear here." />}</Card>; }
