import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useLocation, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { LockKeyhole } from "lucide-react";
import useAuth from "../../hooks/useAuth";
import Button from "../../components/ui/Button";
import Input from "../../components/ui/Input";
import { getApiErrorMessage } from "../../utils/apiError";

export default function LoginPage() { const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [submitting, setSubmitting] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm({ defaultValues: { email: "", password: "" } }); const onSubmit = async (values) => { setSubmitting(true); try { await login(values); toast.success("Welcome back!"); navigate(location.state?.from?.pathname || "/dashboard", { replace: true }); } catch (error) { toast.error(getApiErrorMessage(error, "Unable to sign in.")); } finally { setSubmitting(false); } }; return <main className="grid min-h-screen bg-slate-50 lg:grid-cols-2"><section className="hidden bg-teal-800 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="text-2xl font-bold">Leave<span className="text-teal-300">Flow</span></div><div><p className="text-4xl font-bold leading-tight">Your workforce, in perfect flow.</p><p className="mt-4 max-w-md text-teal-100">A simple, secure place for attendance, leave, and people operations.</p></div><p className="text-sm text-teal-200">Leave & Attendance Management System</p></section><section className="grid place-items-center p-6"><form onSubmit={handleSubmit(onSubmit)} className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><div className="mb-8"><div className="mb-6 text-xl font-bold text-slate-900 lg:hidden">Leave<span className="text-teal-700">Flow</span></div><div className="mb-4 grid size-11 place-items-center rounded-xl bg-teal-100 text-teal-800"><LockKeyhole size={22} /></div><h1 className="text-2xl font-bold text-slate-900">Welcome back</h1><p className="mt-2 text-sm text-slate-600">Sign in to access your workspace.</p></div><div className="space-y-5"><Input label="Email address" type="email" autoComplete="email" placeholder="you@company.com" error={errors.email?.message} {...register("email", { required: "Email is required", pattern: { value: /^\S+@\S+\.\S+$/, message: "Enter a valid email address" } })} /><Input label="Password" type="password" autoComplete="current-password" placeholder="Enter your password" error={errors.password?.message} {...register("password", { required: "Password is required", minLength: { value: 8, message: "Password must be at least 8 characters" } })} /><Button type="submit" className="w-full" loading={submitting}>Sign in</Button></div><p className="mt-6 text-center text-sm text-slate-600">Don't have an account? <Link to="/register" className="font-semibold text-teal-700 transition hover:text-teal-800">Create Account</Link></p></form></section></main>; }
