import { useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import { useLeaveActions, useLeaveTypes } from "../../hooks/useLeave";
import Input from "../../components/ui/Input";
import Select from "../../components/ui/Select";
import TextArea from "../../components/ui/TextArea";
import Button from "../../components/ui/Button";
import Card from "../../components/ui/Card";
import { getApiErrorMessage } from "../../utils/apiError";
const validTypes = ["application/pdf", "image/jpeg", "image/png"];
export default function ApplyLeavePage() { const navigate = useNavigate(); const types = useLeaveTypes(); const { apply } = useLeaveActions(); const [file, setFile] = useState(null); const [progress, setProgress] = useState(0); const { register, handleSubmit, formState: { errors } } = useForm(); const submit = async (values) => { if (file && (!validTypes.includes(file.type) || file.size > 10 * 1024 * 1024)) { toast.error("Use a PDF, JPG, JPEG, or PNG document up to 10 MB."); return; } try { await apply.mutateAsync({ values: { ...values, document: file }, onProgress: setProgress }); toast.success("Leave request submitted successfully."); navigate("/leave/my"); } catch (error) { toast.error(getApiErrorMessage(error)); } }; return <div className="mx-auto mt-6 max-w-2xl"><h1 className="text-2xl font-bold">Apply Leave</h1><p className="mt-1 text-sm text-slate-600">Submit a leave request with an optional supporting document.</p><Card className="mt-6 p-6"><form className="space-y-5" onSubmit={handleSubmit(submit)}><Select label="Leave type" error={errors.leaveTypeId?.message} {...register("leaveTypeId", { required: "Choose a leave type" })}><option value="">Select leave type</option>{(types.data?.leaveTypes || []).map((type) => <option value={type._id} key={type._id}>{type.name}</option>)}</Select><div className="grid gap-5 sm:grid-cols-2"><Input label="Start date" type="date" error={errors.startDate?.message} {...register("startDate", { required: "Start date is required" })} /><Input label="End date" type="date" error={errors.endDate?.message} {...register("endDate", { required: "End date is required" })} /></div><TextArea label="Reason" rows="4" error={errors.reason?.message} {...register("reason", { required: "Reason is required", minLength: { value: 5, message: "Reason must be at least 5 characters" }, maxLength: { value: 500, message: "Reason cannot exceed 500 characters" } })} /><label className="block text-sm font-medium text-slate-700">Supporting document (optional)<input className="mt-1.5 block w-full text-sm" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={(event) => setFile(event.target.files?.[0] || null)} />{file && <span className="mt-2 block text-xs text-slate-500">{file.name} ({Math.ceil(file.size / 1024)} KB)</span>}<span className="mt-1 block text-xs text-slate-500">PDF, JPG, JPEG, or PNG; maximum 10 MB.</span></label>{apply.isPending && progress > 0 && <div className="h-2 overflow-hidden rounded bg-slate-200"><div className="h-full bg-teal-700" style={{ width: `${progress}%` }} /></div>}<Button type="submit" loading={apply.isPending}>Submit request</Button></form></Card></div>; }
