import { CalendarClock, CheckCircle2, CircleX, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import useAuth from "../../hooks/useAuth";
import { useLeaveBalances, useLeaveRequests } from "../../hooks/useLeave";
import StatCard from "../../components/dashboard/StatCard";
import Card from "../../components/ui/Card";
import Button from "../../components/ui/Button";
import Loader from "../../components/ui/Loader";
export default function LeaveDashboardPage() { const { user } = useAuth(); const scope = user.role === "manager" ? "team" : ["hr", "admin"].includes(user.role) ? "organization" : "my"; const requests = useLeaveRequests(scope, { page: 1, limit: 100 }); const balances = useLeaveBalances(user.role === "employee"); if (requests.isLoading || balances.isLoading) return <Loader label="Loading leave dashboard…" />; const all = requests.data?.leaveRequests || []; const counts = (status) => all.filter((request) => request.status === status).length; const upcoming = all.filter((request) => new Date(request.startDate) >= new Date()).length; return <div className="mt-6 space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Leave Dashboard</h1><p className="mt-1 text-sm text-slate-600">Your live leave overview.</p></div>{user.role === "employee" && <Link to="/leave/apply"><Button>Apply Leave</Button></Link>}</div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={CalendarClock} title="Pending Requests" value={counts("pending")} subtitle="Loaded leave requests" tone="amber" /><StatCard icon={CheckCircle2} title="Approved Leaves" value={counts("approved")} subtitle="Loaded leave requests" tone="teal" /><StatCard icon={CircleX} title="Rejected Leaves" value={counts("rejected")} subtitle="Loaded leave requests" tone="rose" /><StatCard icon={WalletCards} title="Upcoming Leave" value={upcoming} subtitle="Loaded future requests" tone="blue" /></section>{user.role === "employee" && <Card className="p-5"><h2 className="font-semibold">Current Leave Balance</h2>{balances.data?.leaveBalances?.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{balances.data.leaveBalances.map((item) => <div className="rounded-lg bg-slate-50 p-4" key={item._id}><p className="font-medium">{item.leaveTypeId?.name}</p><p className="mt-2 text-2xl font-bold text-teal-700">{item.remaining}</p><p className="mt-1 text-xs text-slate-500">{item.used} used of {item.allocated} available</p></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No leave balances are available for this year.</p>}</Card>}</div>; }
