import { useState } from "react";
import toast from "react-hot-toast";
import { LogIn, LogOut } from "lucide-react";
import { useAttendanceActions, useAttendanceDashboard } from "../../hooks/useAttendance";
import Button from "../../components/ui/Button";
import Card from "../../components/ui/Card";
import Loader from "../../components/ui/Loader";
import { formatTime } from "../../utils/attendance";
import { getApiErrorMessage } from "../../utils/apiError";
export default function MarkAttendancePage() { const dashboard = useAttendanceDashboard(); const { punchIn, punchOut } = useAttendanceActions(); const [note, setNote] = useState(""); if (dashboard.isLoading) return <Loader label="Loading today’s attendance…" />; const today = dashboard.data?.todayAttendance; const execute = async (mutation) => { try { await mutation; toast.success("Attendance updated successfully."); } catch (error) { toast.error(getApiErrorMessage(error)); } }; return <div className="mx-auto mt-6 max-w-2xl"><h1 className="text-2xl font-bold">Mark Attendance</h1><p className="mt-1 text-sm text-slate-600">Record your check-in and check-out for today.</p><Card className="mt-6 p-6"><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-sm text-slate-500">Check-in</p><p className="mt-1 text-xl font-bold">{formatTime(today?.punchIn)}</p></div><div><p className="text-sm text-slate-500">Check-out</p><p className="mt-1 text-xl font-bold">{formatTime(today?.punchOut)}</p></div></div>{!today?.punchIn && <label className="mt-6 block text-sm font-medium text-slate-700">Optional note<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength="500" rows="3" className="mt-1.5 w-full rounded-lg border border-slate-300 p-3" placeholder="Add a note for today" /></label>}<div className="mt-6 flex flex-wrap gap-3">{!today?.punchIn && <Button loading={punchIn.isPending} onClick={() => execute(punchIn.mutateAsync(note))}><LogIn size={18} />Check in</Button>}{today?.punchIn && !today?.punchOut && <Button loading={punchOut.isPending} onClick={() => execute(punchOut.mutateAsync())}><LogOut size={18} />Check out</Button>}{today?.punchOut && <p className="text-sm font-medium text-emerald-700">Today’s attendance is complete.</p>}</div></Card></div>; }
